poi_administrators:
    resource: "@PoiBundle/Resources/config/routing/administrators.yml"
    prefix:   /administrators

poi_points:
    resource: "@PoiBundle/Resources/config/routing/points.yml"
    prefix:   /points

poi_ratings:
    resource: "@PoiBundle/Resources/config/routing/ratings.yml"
    prefix:   /ratings

poi_types:
    resource: "@PoiBundle/Resources/config/routing/types.yml"
    prefix:   /types

poi_users:
    resource: "@PoiBundle/Resources/config/routing/users.yml"
    prefix:   /users

poi_main:
    resource: "@PoiBundle/Resources/config/routing/main.yml"
    prefix:   /main

poi_security:
    resource: "@PoiBundle/Resources/config/routing/security.yml"
    prefix:   /

poi_registration:
    resource: "@PoiBundle/Resources/config/routing/registration.yml"
    prefix: /registration

poi_warnings:
    resource: "@PoiBundle/Resources/config/routing/warnings.yml"
    prefix: /warnings

poi_api:
    resource: "@PoiBundle/Controller/ApiController.php"
    prefix: /api
    type: rest

logout:
  path: /logout