changes_index:
    path:     /
    defaults: { _controller: "PoiBundle:Changes:index" }
    methods:  GET

changes_show:
    path:     /{id}/show
    defaults: { _controller: "PoiBundle:Changes:show" }
    methods:  GET

changes_new:
    path:     /new
    defaults: { _controller: "PoiBundle:Changes:new" }
    methods:  [GET, POST]

changes_edit:
    path:     /{id}/edit
    defaults: { _controller: "PoiBundle:Changes:edit" }
    methods:  [GET, POST]

changes_delete:
    path:     /{id}/delete
    defaults: { _controller: "PoiBundle:Changes:delete" }
    methods:  DELETE
