control_index:
    path:     /
    defaults: { _controller: "PoiBundle:Control:index" }
    methods:  GET

control_show:
    path:     /{id}/show
    defaults: { _controller: "PoiBundle:Control:show" }
    methods:  GET

control_new:
    path:     /new
    defaults: { _controller: "PoiBundle:Control:new" }
    methods:  [GET, POST]

control_edit:
    path:     /{id}/edit
    defaults: { _controller: "PoiBundle:Control:edit" }
    methods:  [GET, POST]

control_delete:
    path:     /{id}/delete
    defaults: { _controller: "PoiBundle:Control:delete" }
    methods:  DELETE
