main_ajax:
    path:     /ajax
    defaults: { _controller: "PoiBundle:Main:ajax" }
    methods:  GET

main_index:
    path:     /
    defaults: { _controller: "PoiBundle:Main:index" }
    methods:  [GET, POST]

main_search:
    path:     /search
    defaults: { _controller: "PoiBundle:Main:search" }
    methods:  [GET, POST]