points_index:
    path:     /{page}/index
    defaults: { _controller: "PoiBundle:Points:index", page: 1  }
    methods:  GET

points_show:
    path:     /{id}/show
    defaults: { _controller: "PoiBundle:Points:show" }
    methods:  GET

points_edit:
    path:     /{id}/edit
    defaults: { _controller: "PoiBundle:Points:edit" }
    methods:  [GET, POST]

points_delete:
    path:     /{id}/delete
    defaults: { _controller: "PoiBundle:Points:delete" }
    methods:  DELETE

points_disabled:
    path:     /{page}/disabled
    defaults: { _controller: "PoiBundle:Points:disabled", page: 1 }
    methods:  [GET, POST]

points_enabled:
    path:     /{page}/enabled
    defaults: { _controller: "PoiBundle:Points:enabled", page: 1 }
    methods:  [GET, POST]

points_acceptable:
    path:     /{page}/acceptable
    defaults: { _controller: "PoiBundle:Points:acceptable", page: 1 }
    methods:  [GET, POST]

points_block:
    path:     /{id}/{page}/block
    defaults: { _controller: "PoiBundle:Points:block", page: 1 }
    methods:  [GET, POST]

points_unblock:
    path:     /{id}/{page}/unblock
    defaults: { _controller: "PoiBundle:Points:unblock", page: 1 }
    methods:  [GET, POST]

points_promote:
    path:     /{id}/promote
    defaults: { _controller: "PoiBundle:Points:promote", page: 1 }
    methods:  [GET, POST]

ratingdelete_delete:
    path:     /{ratingId}/{pointId}/delete
    defaults: { _controller: "PoiBundle:Points:ratingDelete" }
    methods:  GET