users_index:
    path:      /{page}/index
    defaults: { _controller: "PoiBundle:Users:index", page: 1 }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "PoiBundle:Users:show" }
    methods:  GET

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "PoiBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "PoiBundle:Users:delete" }
    methods:  DELETE

users_block:
    path:     /{id}/{page}/block
    defaults: { _controller: "PoiBundle:Users:block", page: 1 }
    methods:  [GET]

users_unblock:
    path:     /{id}/{page}/unblock
    defaults: { _controller: "PoiBundle:Users:unblock", page: 1 }
    methods:  [GET]

users_blocked:
    path:     /{page}/blocked
    defaults: { _controller: "PoiBundle:Users:blocked", page: 1 }
    methods:  [GET, POST]

users_unblocked:
    path:     /{page}/unblocked
    defaults: { _controller: "PoiBundle:Users:unblocked", page: 1 }
    methods:  [GET, POST]