warnings_index:
    path:     /
    defaults: { _controller: "PoiBundle:Warnings:index" }
    methods:  GET

warnings_show:
    path:     /{id}/show
    defaults: { _controller: "PoiBundle:Warnings:show" }
    methods:  GET

warnings_new:
    path:     /new
    defaults: { _controller: "PoiBundle:Warnings:new" }
    methods:  [GET, POST]

warnings_edit:
    path:     /{id}/edit
    defaults: { _controller: "PoiBundle:Warnings:edit" }
    methods:  [GET, POST]

warnings_delete:
    path:     /{id}/delete
    defaults: { _controller: "PoiBundle:Warnings:delete" }
    methods:  DELETE
