<?php

namespace PoiBundle\Repository;

/**
 * AdministratorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();

        $query
            ->select(['Administrators'])
            ->from('PoiBundle:Administrators', 'Administrators');

        try {
            return $query->getQuery();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
