<?php

namespace PoiBundle\Repository;

/**
 * PermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionsRepository extends \Doctrine\ORM\EntityRepository
{

}
