<?php

namespace PoiBundle\Repository;

/**
 * RatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAvargeRating($pointid){
        $query = $this->getEntityManager()->createQueryBuilder();

        $query
            ->select('avg(Rating.rating)')
            ->from('PoiBundle:Ratings', 'Rating')
            ->innerJoin('Rating.point', 'Point')
            ->where('Point.id = :pointid')
            ->setParameter('pointid', $pointid);

        try {
            return $query->getQuery()->getSingleScalarResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
