<?php

namespace PoiBundle\Repository;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();

        $query
            ->select(['Types'])
            ->from('PoiBundle:Types', 'Types');

        try {
            return $query->getQuery();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
