<?php

namespace PoiBundle\Repository;

/**
 * VersionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLatestResult(){
        $query = $this->getEntityManager()->createQueryBuilder();

        $last_entity = $query
            ->select('Version')
            ->from('PoiBundle:Versions', 'Version')
            ->orderBy('Version.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return $last_entity;
    }

}
