<?php

namespace PoiBundle\Repository;

/**
 * WarningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarningsRepository extends \Doctrine\ORM\EntityRepository
{
}
